name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 1、生成静态文件
      - name: Build
        run: npm install && npm run build

      # 2、部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: xwzkj/xwzkj.github.io
          BRANCH: main
          FOLDER: dist
          #注意这里的 public 是仓库根目录下的 public，也就是 npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`

      # # 5、部署到 somenzz.cn 服务器
      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@4.1
      #   with:
      #     # 这里是 rsync 的参数 switches: -avzh --delete --exclude="" --include="" --filter=""
      #     switches: -avzh
      #     path: public/
      #     remote_path: /home/ubuntu/public/
      #     remote_host: somenzz.cn
      #     remote_port: 22
      #     remote_user: ubuntu
      #     remote_key: ${{ secrets.MY_UBUNTU_RSA_PRIVATE_KEY }}