name: Release
on:
    push:
      tags:
        - '*'  # 任何标签的推送都会触发

jobs:
  release:
    # 服务器环境：最新版 windows
    runs-on: windows-latest
    steps:
      # 拉取代码
      - name: pull
        uses: actions/checkout@v2
        with:
          persist-credentials: false  

      - name: 构建
        run: npm install && npm run build:win

      - name: 创建发行版
        uses: ncipollo/release-action@v1.14.0
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            artifacts: 'dist/*.exe'
            body: '由 GitHub Actions 自动发布'